CI に clippy を追加しました
ryuma017/twimi pull request #25
Opened 2022-11-08 08:31 UTC by ryuma017

- closes: #24

2022-11-08 08:36 UTC, siketyan requested changes

2022-11-08 08:36 UTC, siketyan commented on .github/workflows/ci.yml
> +  clippy:
いろいろ同じ部分が多いので fmt とおなじジョブにした方が良いのではと思いました

2022-11-08 08:36 UTC, siketyan commented on .github/workflows/ci.yml
> +  clippy:
あと MySQL はいらないきがする

2022-11-08 08:43 UTC, ryuma017 commented on .github/workflows/ci.yml
> +  clippy:
> いろいろ同じ部分が多いので fmt とおなじジョブにした方が良いのではと思いました
おっしゃるとおりです..修正します

2022-11-08 08:48 UTC, ryuma017 commented on .github/workflows/ci.yml
> +  clippy:
> あと MySQL はいらないきがする

sqlx はコンパイル時に静的に型検査するのでこれからクエリ書いたときに MySQL ないと落ちる気がします🤔

2022-11-08 08:54 UTC, siketyan commented on .github/workflows/ci.yml
> +  clippy:
@ryuma017 

たぶんその型検査で DB にアクセスはしてないと思います．
ローカルですが cargo clippy できちゃいました (MySQL とか何も立ててない)

<img width="682" alt="image" src="https://user-images.githubusercontent.com/12772118/200519366-1f79fec1-10ed-487f-9e27-94251a373c71.png">

2022-11-08 08:56 UTC, ryumatag commented on .github/workflows/ci.yml
> +  clippy:
今は helth check で `select 1` しかしてないからじゃないでしょうか？

2022-11-08 09:13 UTC, ryuma017 commented on .github/workflows/ci.yml
> +  clippy:
@siketyan 
`lint` でまとめてみました🫡

2022-11-08 10:11 UTC, siketyan approved these changes

2022-11-09 00:43 UTC, ryumatag commented
ありがとうございます🫡

2022-11-09 00:43 UTC, merged